name: Docker Publish

on:
  push:
    branches: [main]
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Call Docker-Publish Function
        uses: dagger/dagger-for-github@v6.1.0
        if: always()
        env: 
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
        with:
          version: "latest"
          verb: call
          module: github.com/bishal7679/harbor-cli@v0.6.2
          args: docker-publish --directory-arg=. --reg-username=${{ env.REGISTRY_USERNAME }} --reg-password=${{ env.REGISTRY_PASSWORD }} --private-key=${{ env.COSIGN_KEY }} --password=${{ env.COSIGN_PASSWORD }}
